### ISSUE TITLE
README 

### ISSUE THREAD

**Issue by asteves** [dlab-berkeley/R-functional-programming#5]
@aculich 

Right now the readme references seems out of place with D-Lab style (e.g [R-Fundamentals](https://github.com/dlab-berkeley/R-Fundamentals)). 

I feel like we should change to bring consistency.

**Comment by aculich** [comment]
check with @pssachdeva about curriculum updates moving forward and also check out the new [D-Lab Workshop Style Guide](https://docs.google.com/document/d/14qKQlkXBN_wp2IrBrjG0-AIcH-UYlzoHGmbHdK3PA-o/edit)

**Comment by asteves** [comment]
@pssachdeva Thoughts?
